### ISSUE TITLE
Error Raised: TypeError: list indices must be integers, not unicode

### ISSUE THREAD

**Issue by wenlibin02** [bibcure/title2bib#3]
Hello, 

Recently when I use the title2bib to search for literature by title, it gives error like the following: 

command: `$title2bib 'Nanotwinned diamond with unprecedented hardness and stability'`
error message: 

	Traceback (most recent call last):
	  File "/usr/local/bin/title2bib", line 85, in <module>
		main()
	  File "/usr/local/bin/title2bib", line 71, in main
		found, bib = get_bib_from_title(title, get_first)
	  File "/usr/local/lib/python2.7/site-packages/title2bib/crossref.py", line 86, in get_bib_from_title
		found, item = get_from_title(title, get_first)
	  File "/usr/local/lib/python2.7/site-packages/title2bib/crossref.py", line 50, in get_from_title
		items = r.json()["message"]["items"]
	TypeError: list indices must be integers, not unicode

I am using python 2.7.15 on Mac OSX. The command works well a few weeks ago. 

I also tried to update title2bib to version 0.4.0 using pip, but still have the issue.

Thanks a lot.

Libin

**Comment by kirk86** [comment]
I can confirm getting kind of similar error
```
raceback (most recent call last):
  File "/home/user/bin/title2bib", line 85, in <module>
    main()
  File "/home/user/bin/title2bib", line 71, in main
    found, bib = get_bib_from_title(title, get_first)
  File "/home/user/lib/python3.7/site-packages/title2bib/crossref.py", line 86, in get_bib_from_title
    found, item = get_from_title(title, get_first)
  File "/home/user/lib/python3.7/site-packages/title2bib/crossref.py", line 50, in get_from_title
    items = r.json()["message"]["items"]
TypeError: list indices must be integers or slices, not str

```

**Comment by TjWallas** [comment]
I am also getting the same error. Any help here?

**Comment by wenlibin02** [comment]
Try the quick fix in the recent pull request: https://github.com/bibcure/title2bib/pull/4/commits/6789a4b3c111905571a8070c5b8d84d310c83a6a

**Comment by kirk86** [comment]
@wenlibin02 Does it work for you?

**Comment by wenlibin02** [comment]
> @wenlibin02 Does it work for you?

Yes, after I applied the code modification in the commit previously mentioned.
